### model
model_name_or_path: baidu/ERNIE-4.5-0.3B-Paddle
tensor_parallel_degree: 1
output_dir: None

### server
# ref: https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/zh/optimal_deployment/ERNIE-4.5-0.3B-Paddle.md
max_model_len: 131072
port: 8188
quantization: wint4

### chat
max_new_tokens: 8192
top_p: 0.7
temperature: 0.95
