name: Codestyle

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  PR_ID: ${{ github.event.pull_request.number }}
  BRANCH: ${{ github.event.pull_request.base.ref }}
  TASK: ERNIE-Codestyle-${{ github.event.pull_request.number }}
jobs:
  Lint:
    name: Lint
    runs-on: [self-hosted, ernie-cpu]
    permissions:
      pull-requests: write
      contents: read
      id-token: write
    steps:
      - name: Run Container
        env:
          work_dir: ${{ github.workspace }}
        run: |
          container_name=${TASK}-$(date +%Y%m%d-%H%M%S)
          echo "container_name=${container_name}" >> "$GITHUB_ENV"
          docker_image="iregistry.baidu-int.com/paddlecloud/base-images:paddlecloud-ubuntu20.04-gcc12.2-cuda12.3-cudnn9.0-nccl2.20.3.1-openmpi4.1.5"
          docker run -d -t --name ${container_name} --net=host -v /dev/shm:/dev/shm --shm-size=32G \
            -v $work_dir/../../..:$work_dir/../../.. \
            -v $work_dir:/workspace \
            -v /root/.cache/:/root/.cache/ \
            -e BRANCH \
            -e PR_ID \
            -e work_dir \
            -w /workspace ${docker_image}

      - name: Install Dependencies
        run: |
          docker exec -t ${container_name} /bin/bash -c '
          python -m pip install --upgrade pip -i https://pypi.tuna.tsinghua.edu.cn/simple
          '

      - name: Get Diff
        env:
          work_dir: ${{ github.workspace }}
        run: |
          docker exec -t ${container_name} /bin/bash -c '
          rm -rf ERNIE
          source $work_dir/../../../proxy
          git clone https://github.com/PaddlePaddle/ERNIE.git
          cd ERNIE
          git config --global user.name "PaddleCI"
          git config --global user.email "paddle_ci@example.com"
          git fetch origin pull/${PR_ID}/head
          git checkout -b origin_pr FETCH_HEAD
          git remote add upstream https://github.com/PaddlePaddle/ERNIE.git
          git checkout -b test_pr upstream/${BRANCH}
          git merge --no-edit origin_pr
          git diff --numstat ${BRANCH} -- | awk "{print \$NF}"
          PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple pre-commit run --files setup.py
          make lint
          '

      - name: Terminate And Delete the Container
        if: always()
        run: |
          docker stop $container_name 2>/dev/null || true
          docker rm -f $container_name 2>/dev/null || true
