name: Test

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true
  
jobs:
  Test:
    name: Test
    runs-on: [self-hosted, 4gpu]
    steps:
      - name: Start Docker 
        run: |
          if [ ! "$(docker ps -q -f name=ERNIE_CI_Container)" ]; then
            echo "Starting container ERNIE_CI_Container"
            docker start ERNIE_CI_Container
          else
            echo "ERNIE_CI_Container already running"
          fi
      - name: Cleanup Environment Cache
        run: docker exec -t ERNIE_CI_Container /bin/bash -c '
          rm -rf /workspace/* /workspace/.[!.]* /workspace/..?*'
      - name: Get Repo
        env:
          ACTIONS_RUNNER_FORCED_INTERNAL_NODE_VERSION: node16
          ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION: node16
          ACTIONS_ALLOW_UNSECURE_NODE_VERSION: true
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Prepare Model
        run: docker exec -t ERNIE_CI_Container /bin/bash -c '
            cp -r /home/ERNIE_Model/* /workspace/ '
      - name: Install erniekit
        run: docker exec -t ERNIE_CI_Container /bin/bash -c '
          pip install -e.'
      - name: Runing case
        run: docker exec -t ERNIE_CI_Container /bin/bash -c '
          make test'
